<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
</head>
<style media="screen">
  .glyphicon{
    color:black;
  }
</style>
  <body>
    <nav class="navbar bg-dark navbar-dark fixed-top " >
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand " href="#">PC's Aguilar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#collapsibleNavbar"><span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse " id="collapsibleNavbar">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
            </ul>
          </div>
        </div>

          <form class="mt-0"action="index.html" method="post">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Buscar...">
              <div class="input-group-btn">
                <button type="button" class="btn btn-default">
                  <span class="glyphicon glyphicon-search"></span>
                </button>
              </div>
            </div>
          </form>

          <ul class="nav navbar-pills ">
            <li class="nav-item"><a class="nav-link" href="#">
              <span class="glyphicon glyphicon-search"></span> Entrar</a></li>
            <li class="nav-item"><a class="nav-link" href="#"> Registrase</a></li>
            <li class="nav-item"><a class="nav-link" href="#"> Carrito</a></li>
          </ul>
      </div>
      <div class="carousel-item">
        <img src="la.jpg" alt="Los Angeles">
        <div class="carousel-caption">
          <h3>Los Angeles</h3>
          <p>We had such a great time in LA!</p>
        </div>
      </div>

      <div class="row">
    <?php
      foreach ($DATOS as $DATO) {
    ?>
    <div class="card col-3" style= "width:400px; margin: 10px;" >
      <img class="card-img-top" src="https://thumb.pccomponentes.com/w-530-530/articles/13/134039/1340390.jpg" alt="Card image" style="width:100%">
    <div class="card-body">
        <h4 class="card-title"><?php echo $DATO['NAME'] ?> </h4>
        <p class="card-text"><?php echo $DATO['PRICE'] ?> €</p>
        <a href="#" class="btn btn-primary">Comprar</a>
      </div>
    </div>";
      <?php
      }
        ?>
    </nav>
  </body>
</html>
