<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
</head>
  <body>
    <p style="color:red;">Error al iniciar sesion vuelve a intentarlo de nuevo.</p>
    <div class="container">

      <form action="index.php?controller=usuarios&action=login" method="post">
        <div class="form-group">
          <label for="usuario">Usuario:</label>
          <input type="text" class="form-control" name="username" id="username" placeholder="Usuario..." required>
        </div>
        <div class="form-group">
          <label>Contraseña:</label>
          <input type="password" class="form-control" name="password" placeholder="Contraseña..." required>
        </div>
        <button  type="submit" name="login" class="btn btn-primary">Entrar</button>
      </form>
    </div>
  </body>
</html>
